- name: installing k8s and joining worker node with master
  hosts: k8sworker
  become: yes
  
  tasks:
   - name: Add Docker's official GPG key
     apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

   - name: add stable docker repo
     apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present

   - name: add k8s key value
     apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

   - name: add k8s stable repo
     apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      filename: /etc/apt/sources.list.d/kubernetes
      state: present

   - name: install docker kubectl kubelet and kubeadm
     shell: apt-get update && apt-get install -y docker-ce=18.06.1~ce~3-0~ubuntu kubelet=1.13.5-00 kubeadm=1.13.5-00 kubectl=1.13.5-00 && apt-mark hold docker-ce kubelet kubeadm kubectl
     args:
        warn: no

   - name: add ubuntu user to docker group
     shell: usermod -aG docker $USER

   - name: Enable iptables bridge call
     shell: echo "net.bridge.bridge-nf-call-iptables=1" | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
     register: result

   - debug: msg={{ result.stdout }}

   - name: join master node
     shell: kubeadm join 172.31.1.1:6443 --token 680cy6.zyvy38w0u2ctv431 --discovery-token-ca-cert-hash sha256:ffdf4b322a0ce153067f475840f3a564b78d0752219d410fe603b5e2016b5937
     args:
        warn: no
   - pause:
         seconds: 30

- name: Checking nodes on master
  hosts: k8smaster
  become: false
  tasks:
   - name: Check nodes
     shell: kubectl get nodes
     register: result
   - debug: msg={{ result.stdout }}
