- name: Install Oracle Java and Maven
  hosts: java
  become: true
  
  tasks:
  - name: Set authorized key for user ubuntu copying it from current user
     authorized_key:
            user: ubuntu
            state: present
            key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

  - include: tasks/java-mvn/java.yml
  - include: tasks/java-mvn/mvn.yml
