    - name: Copy maven tar file
      copy: src=apache-maven-3.6.2-bin.tar.gz dest=/sites mode=0755

    - name: Sleep for 15 seconds and continue with play
      wait_for:
        timeout: 15

    - name: Extract maven tar file
      unarchive:
        src: /sites/apache-maven-3.6.2-bin.tar.gz
        dest: /sites
        remote_src: yes
      become_user: ubuntu

    - name: create space after last line
      shell: echo " " | tee -a ~/.bashrc
      become_user: ubuntu

    - name: add maven home and path to bashrc file
      lineinfile:
          dest: ~/.bashrc
          regexp: '^#M2 Home'
          line: "{{ item }}"
          state: present
      with_items:
           - "{{ '#M2_Home' }}"
           - "{{ 'export M2_HOME=/sites/apache-maven-3.6.2' }}"
           - "{{ 'export PATH=$M2_HOME/bin:$PATH' }}"
      become_user: ubuntu

    - name: Create symbolic link for maven
      file:
         src: /sites/apache-maven-3.6.2/bin/mvn
         dest: /usr/bin/mvn
         state: link

    - debug: msg="Maven Installation is complete.. Checking version"

    - name: Check Maven Version
      shell: mvn -v 2>&1 | awk -F'(' '/Maven/ {print $1}' | head -1
      register: result
    - debug: msg={{ result.stdout }}

    - name: removing maven tar file from /sites
      file:
        path: /sites/apache-maven-3.6.2-bin.tar.gz
        state: absent

